#!/usr/bin/env bash

# This script enables 1440p @ 120 Hz on Asus PG278Q, in particular on Intel HD Graphics.
#
# "Why not 144 Hz?"
#
#   $ cvt 2560 1440 144 --reduced
#   ERROR: Multiple of 60Hz refresh rate required for  reduced blanking.

set -euo pipefail

if [ -z "${OUTPUT:-}" ]; then
  # We don't use xrandr to get suggested outputs because that often causes the screens to go black for several seconds for some reason.
  echo "Environment variable OUTPUT empty or not set. Please set it to the output to which the monitor is connected (e.g. 'DP-1'; see \`xrandr\`)."
  exit 1
fi
output=${OUTPUT}

mode_name="2560x1440R" # Copied from the modeline generated by `cvt`.
echo "Mode name is '${mode_name}'."

if xrandr | grep -Eq "^ +${mode_name} +"; then
  echo "Mode exists."
else
  echo "Creating mode '${mode_name}' …"
  # 💡 Modeline generated by `cvt 2560 1440 120 --reduced`. Reduced blanking is necessary.
  xrandr --newmode "${mode_name}"  497.25  2560 2608 2640 2720  1440 1443 1448 1525 +hsync -vsync
fi
wait

echo "Adding mode to output ${output} …"
sleep 1
xrandr --addmode ${output} ${mode_name}
wait

echo "Applying mode …"
sleep 1
xrandr --output ${output} --mode ${mode_name}
wait
